import Foundation
@main struct Checks {
 static func main() {
    var checks = 0
    func expect(_ condition: Bool, _ name: String) { precondition(condition, name); checks += 1 }
    func sample(_ time: Double, _ x: Double = 0.25, _ y: Double = 0.5, _ count: Int = 1, _ id: Int = 1) -> TouchSample { TouchSample(count: count, id: id, x: x, y: y, time: time) }
    func run(_ frames: [TouchSample]) -> [TapSide] { var r = TapRecognizer(); return frames.compactMap { r.consume($0) } }
    expect(run([sample(1),sample(1.1,0,0,0)]) == [.left], "left tap")
    expect(run([sample(1,0.75),sample(1.1,0,0,0)]) == [.right], "right tap")
    expect(run([sample(1),sample(1.3,0,0,0)]).isEmpty, "long rest")
    expect(run([sample(1),sample(1.01,0,0,0)]).isEmpty, "noise")
    expect(run([sample(1),sample(1.05,0.32),sample(1.1,0,0,0)]).isEmpty, "scroll movement")
    expect(run([sample(1),sample(1.04,0.25,0.5,2),sample(1.1,0,0,0)]).isEmpty, "multiple fingers")
    expect(run([sample(1,0.5),sample(1.1,0,0,0)]).isEmpty, "center seam")
    expect(run([sample(1,0.01),sample(1.1,0,0,0)]).isEmpty, "edge")
    expect(run([sample(1),sample(1.05,0.25,0.5,1,2),sample(1.1,0,0,0)]).isEmpty, "identity replacement")
    expect(run([sample(1),sample(0.9),sample(1.1,0,0,0)]).isEmpty, "out of order")
    expect(run([sample(1),sample(1.05,.nan),sample(1.1,0,0,0)]).isEmpty, "nonfinite")
    expect(run([sample(1),sample(1.1,0,0,0),sample(1.18),sample(1.27,0,0,0)]) == [.left,.left], "double tap")
    expect(run([sample(1),sample(1.1,0,0,0),sample(1.11),sample(1.14,0,0,0)]) == [.left], "debounce")
    var r = TapRecognizer(); _ = r.consume(sample(1)); r.cancel()
    expect(r.consume(sample(1.1,0,0,0)) == nil, "physical click cancellation")
    _ = r.consume(sample(1.3)); expect(r.consume(sample(1.4,0,0,0)) == .left, "recovery")
    var recovery = TapRecognizer()
    _ = recovery.consume(sample(2))
    recovery.consumeSuppressed(sample(2.05,0,0,0))
    _ = recovery.consume(sample(2.2))
    expect(recovery.consume(sample(2.3,0,0,0)) == .left, "first tap after suppressed release")
    for i in 0..<100 {
        let t = 3 + Double(i)
        _ = recovery.consume(sample(t))
        recovery.consumeSuppressed(sample(t+0.02))
        recovery.consumeSuppressed(sample(t+0.04,0,0,0))
        _ = recovery.consume(sample(t+0.2,0.75))
        expect(recovery.consume(sample(t+0.3,0,0,0)) == .right, "repeated selection recovery")
    }
    recovery.cancel()
    recovery.consumeSuppressed(TouchSample(count: 0, id: 0, x: 0, y: 0, time: 104, valid: false))
    _ = recovery.consume(sample(104.1))
    expect(recovery.consume(sample(104.2,0,0,0)) == nil, "invalid release cannot rearm")
    var newSession = TapRecognizer()
    _ = newSession.consume(sample(5000))
    _ = newSession.consume(sample(5000.1,0,0,0))
    // A reconnected device may restart its timestamp origin. The engine must
    // reset and require a clear boundary before accepting this new session.
    newSession.reset(); newSession.cancel()
    _ = newSession.consume(sample(0.01,0,0,0))
    _ = newSession.consume(sample(0.1))
    expect(newSession.consume(sample(0.2,0,0,0)) == .left, "new device timestamp origin")
    expect(run([sample(1),sample(1.030,0,0,0),sample(1.055),sample(1.085,0,0,0)]) == [.left,.left], "fast double tap with real release gap")
    expect(run([sample(1),sample(1.030,0,0,0),sample(1.035),sample(1.070,0,0,0)]) == [.left], "contact bounce is not a double tap")
    expect(run([sample(1),sample(1.05,0.29),sample(1.1,0,0,0)]) == [.left], "small natural finger motion")
    expect(run([sample(1),sample(1.05,0.30),sample(1.1,0,0,0)]).isEmpty, "movement beyond tolerance")
    expect(run([sample(1),sample(1.24,0,0,0)]) == [.left], "slightly longer deliberate tap")
    expect(run([sample(1),sample(1.26,0,0,0)]).isEmpty, "rest still rejected")
    var gate = TapSuppression()
    gate.observe(.button, at: 1)
    expect(gate.isActive(at: 1.03) && !gate.isActive(at: 1.05), "button cooldown releases quickly")
    gate.observe(.scrollOrDrag, at: 2)
    gate.observe(.button, at: 2.01)
    expect(gate.isActive(at: 2.10) && !gate.isActive(at: 2.13), "button cannot shorten scrolling cooldown")
    gate.observe(.interruption, at: 3)
    expect(gate.isActive(at: 3.10) && !gate.isActive(at: 3.13), "system interruption retains protection")
    var afterClick = TapRecognizer()
    afterClick.consumeSuppressed(sample(4.01,0,0,0))
    _ = afterClick.consume(sample(4.05))
    expect(afterClick.consume(sample(4.09,0,0,0)) == .left, "first complete tap after physical click")
    print("PASS: \(checks) tap recognizer checks")
 }
}
